server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://avnadmin:YOUR_AIVEN_PASSWORD@mysql-2ba78369-stu-efa2.i.aivencloud.com:22132/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: ${AIVEN_DB_PASSWORD:YOUR_AIVEN_DB_PASSWORD_HERE}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

app:
  cors:
    allowed-origin: http://localhost:5173

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

sendgrid:
  api-key: ${SENDGRID_API_KEY:YOUR_SENDGRID_API_KEY_HERE}
  from-email: ${SENDGRID_FROM_EMAIL:YOUR_SENDGRID_FROM_EMAIL_HERE}
