version: '3.8'

services:
  backend:
    build: 
      context: .
      args:
        BUILD_TIMESTAMP: ${BUILD_TIMESTAMP:-$(date +%s)}
    ports:
      - "8080:8080"
    environment:
      - AIVEN_DB_PASSWORD=${AIVEN_DB_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - APP_CORS_ALLOWED_ORIGIN=${APP_CORS_ALLOWED_ORIGIN}
    env_file:
      - .env
