version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AIVEN_DB_PASSWORD=${AIVEN_DB_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
    env_file:
      - .env
