server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://avnadmin:${AIVEN_DB_PASSWORD}@mysql-2ba78369-stu-efa2.i.aivencloud.com:22132/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: ${AIVEN_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format_sql: false

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN:*}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}

logging:
  level:
    com.example.simple: INFO
    org.springframework: WARN
